### ISSUE TITLE
基于该项目增加功能请求许可

### ISSUE THREAD

**Issue by shiwk20** [zqthu/thu_cloud_download#2]
大佬好，我在您的项目的基础上增加了下载子目录和下载自己资料库中文件的功能，发布在我的[github仓库](https://github.com/shiwk20/TsinghuaCloudDownload)里面了，在README中说明了是基于您的项目，希望获得您的许可。

**Comment by zqthu** [comment]
感谢您对本项目的关注，版权许可依照MIT License即可
